#!/bin/bash
# Test Script for Bug Fixes

echo "======================================"
echo "Future of Work Platform - Test Guide"
echo "======================================"
echo ""
echo "🌐 APPLICATION URLS:"
echo "   Frontend: http://localhost:3000"
echo "   Backend API: http://localhost:8000"
echo "   API Documentation: http://localhost:8000/docs"
echo ""
echo "======================================"
echo "TEST 1: Score Persistence Fix"
echo "======================================"
echo "1. ✓ Login to existing user account"
echo "2. ✓ Check Dashboard - scores should NOT be 0%"
echo "3. ✓ Complete a quiz from 'Knowledge Tests' card"
echo "4. ✓ Return to Dashboard - scores updated"
echo "5. ✓ Logout (top right button)"
echo "6. ✓ Login again"
echo "7. ✓ Verify Dashboard still shows your scores (NOT 0%)"
echo ""
echo "Expected Result: ✓ Scores persist after logout/login"
echo ""
echo "======================================"
echo "TEST 2: Peer Benchmarking"
echo "======================================"
echo "Setup:"
echo "  - Need 2+ users with SAME specialization"
echo "  - Each user must complete at least 1 quiz"
echo ""
echo "Steps:"
echo "1. ✓ User 1: Register → Complete onboarding → Select specialization"
echo "2. ✓ User 1: Complete at least one quiz"
echo "3. ✓ User 1: Click 'Peer Benchmarking' card on dashboard"
echo "   (Should see 'Not enough data' - only 1 user)"
echo ""
echo "4. ✓ Logout User 1"
echo "5. ✓ User 2: Register → Complete onboarding → Select SAME specialization"
echo "6. ✓ User 2: Complete at least one quiz"
echo "7. ✓ User 2: Click 'Peer Benchmarking' card"
echo ""
echo "Expected Results:"
echo "  ✓ Overall percentile rank displayed"
echo "  ✓ 4 comparison cards (Technical, Soft Skills, Leadership, Overall)"
echo "  ✓ Progress bars showing your score vs peer average"
echo "  ✓ Status indicators (trending up/down/stable)"
echo "  ✓ Common strengths section (green cards)"
echo "  ✓ Common gaps section (orange cards)"
echo "  ✓ Total peers count matches number of users"
echo ""
echo "======================================"
echo "TEST 3: Dashboard Navigation"
echo "======================================"
echo "1. ✓ Login to any user account"
echo "2. ✓ Verify Dashboard shows:"
echo "   - Welcome message with user name"
echo "   - Specialization name (not 'Not specified')"
echo "   - Readiness score (circular progress)"
echo "   - 4 score breakdowns (Technical, Soft Skills, Leadership, Overall)"
echo "   - 4 quick access cards:"
echo "     • Knowledge Tests"
echo "     • Peer Benchmarking (NEW)"
echo "     • Skill-Based Exercise"
echo "     • Real-World Simulation"
echo ""
echo "3. ✓ Click 'Peer Benchmarking' card"
echo "4. ✓ Should navigate to /peer-benchmark page"
echo ""
echo "======================================"
echo "CONTAINER STATUS:"
echo "======================================"
docker-compose ps
echo ""
echo "======================================"
echo "TROUBLESHOOTING:"
echo "======================================"
echo ""
echo "If scores still show 0%:"
echo "  1. Check browser console (F12) for errors"
echo "  2. Clear localStorage: localStorage.clear() in console"
echo "  3. Logout and login again"
echo "  4. Complete a quiz to trigger refresh"
echo ""
echo "If peer benchmarking shows 'error':"
echo "  1. Check if user has a specialization selected"
echo "  2. Verify at least 2 users in same specialization"
echo "  3. Both users must have completed at least 1 quiz"
echo "  4. Check backend logs: docker-compose logs backend"
echo ""
echo "If specialization shows 'Not specified':"
echo "  1. Complete onboarding flow fully"
echo "  2. Ensure specialization is selected during signup"
echo "  3. Logout and login to refresh data"
echo ""
echo "======================================"
echo "Quick Commands:"
echo "======================================"
echo "View backend logs:    docker-compose logs backend -f"
echo "View frontend logs:   docker-compose logs frontend -f"
echo "Restart backend:      docker-compose restart backend"
echo "Restart all:          docker-compose restart"
echo "Stop all:             docker-compose down"
echo "Start all:            docker-compose up -d"
echo ""
echo "======================================"
echo "Ready to test! Open http://localhost:3000"
echo "======================================"
