"""add_goals_and_journal_tables

Revision ID: 0184ea910800
Revises: a37388c9e015
Create Date: 2025-11-15 08:03:54.314224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0184ea910800'
down_revision: Union[str, Sequence[str], None] = 'a37388c9e015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('journal_entries', 'prompt',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.add_column('peer_benchmarks', sa.Column('avg_readiness_score', sa.Float(), nullable=False))
    op.add_column('peer_benchmarks', sa.Column('avg_technical_score', sa.Float(), nullable=False))
    op.add_column('peer_benchmarks', sa.Column('avg_soft_skills_score', sa.Float(), nullable=False))
    op.add_column('peer_benchmarks', sa.Column('avg_leadership_score', sa.Float(), nullable=False))
    op.add_column('peer_benchmarks', sa.Column('median_readiness_score', sa.Float(), nullable=False))
    op.alter_column('peer_benchmarks', 'specialization_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('peer_benchmarks', 'total_users',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('peer_benchmarks', 'last_updated',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_column('peer_benchmarks', 'avg_leadership')
    op.drop_column('peer_benchmarks', 'avg_technical')
    op.drop_column('peer_benchmarks', 'avg_readiness')
    op.drop_column('peer_benchmarks', 'median_readiness')
    op.drop_column('peer_benchmarks', 'avg_soft_skills')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('peer_benchmarks', sa.Column('avg_soft_skills', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('peer_benchmarks', sa.Column('median_readiness', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('peer_benchmarks', sa.Column('avg_readiness', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('peer_benchmarks', sa.Column('avg_technical', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('peer_benchmarks', sa.Column('avg_leadership', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('peer_benchmarks', 'last_updated',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('peer_benchmarks', 'total_users',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('peer_benchmarks', 'specialization_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('peer_benchmarks', 'median_readiness_score')
    op.drop_column('peer_benchmarks', 'avg_leadership_score')
    op.drop_column('peer_benchmarks', 'avg_soft_skills_score')
    op.drop_column('peer_benchmarks', 'avg_technical_score')
    op.drop_column('peer_benchmarks', 'avg_readiness_score')
    op.alter_column('journal_entries', 'prompt',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    # ### end Alembic commands ###
